dependencies:
- name: mongodb
  version: ~7.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mongodb.enabled
- name: rabbitmq
  version: ~6.4
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: rabbitmq.enabled
- name: elasticsearch2
  alias: elasticsearch
  version: ~0.1
  repository: https://opensource.ncsa.illinois.edu/charts/
  condition: elasticsearch.enabled
