dependencies:
- name: mongodb
  version: ~7.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mongodb.enabled
- name: rabbitmq
  version: ~6.4
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: rabbitmq.enabled
