{{- if .Values.users }}
{{- $mongodburi := include "clowder.mongodburi" . }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "clowder.name" . }}-init
  labels:
{{ include "clowder.labels" . | indent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    "helm.sh/hook-weight": "5"
spec:
  template:
    metadata:
      name: {{ include "clowder.name" . }}-init
      labels:
{{ include "clowder.labels" . | indent 8 }}
    spec:
      {{- with .Values.hooks.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      restartPolicy: Never
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.imagePullSecrets | indent 8 }}
      {{- end }}
      initContainers:
        - name: check-mongo
          image: clowder/clowder-check:latest
          command: ['./check_mongodb']
          env:
            - name: MONGO_URI
              value: {{ $mongodburi | quote }}
      containers:
{{- range $index, $element := .Values.users }}
        - name: mongo-add-user-{{ $index }}
          image: "{{ $.Values.image.repository }}/mongo-init:develop"
          env:
            - name: MONGO_URI
              value: {{ $mongodburi | quote }}
{{- if .username }}
            - name: USERNAME
              value: {{ .username | quote }}
{{- end }}
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}
                  key: "password-{{ $index }}"
            - name: EMAIL_ADDRESS
              value: {{ .email | quote }}
            - name: FIRST_NAME
              value: {{ .firstname | quote }}
            - name: LAST_NAME
              value: {{ .lastname | quote }}
            - name: ADMIN
              value: {{ .admin | quote }}
{{ end }}
{{ end }}
