apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pecan.fullname" . }}-config
  labels:
{{ include "pecan.labels" . | indent 4 }}
data:
  database.yaml: |-
    production:
      adapter: postgis
      encoding: utf8
      reconnect: false
      database: <%= ENV['BETYDATABASE'] %>
      pool: 5
      username: <%= ENV['BETYUSER'] %>
      password: <%= ENV['BETYPASSWORD'] %>
      host: postgis
      port: 5432
  nginx.conf: |-
    map $http_upgrade $connection_upgrade {
      default upgrade;
      ''      close;
    }

    server {
      listen 80;

      location {{ .Values.rstudio.path }} {
        rewrite ^{{ .Values.rstudio.path }}(.*)$ /$1 break;
        proxy_pass http://localhost:8787;
        proxy_redirect http://localhost:8787/ $scheme://$http_host{{ .Values.rstudio.path }};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 20d;
      }
    }
