apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pecan.fullname" . }}
  labels:
{{ include "pecan.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.pecan.password }}
  pecan-password:  {{ .Values.pecan.password | b64enc | quote }}
  {{- else }}
  pecan-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
