apiVersion: v1
kind: Service
metadata:
  name: {{ include "pecan.fullname" . }}-docs
  labels:
{{ include "pecan.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: pecan-docs
      port: 80
      targetPort: pecan-docs
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "pecan.name" . }}-docs
    app.kubernetes.io/instance: {{ .Release.Name }}
