apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "betydb.fullname" . }}-config
  labels:
{{ include "betydb.labels" . | indent 4 }}
data:
  database.yaml: |-
    production:
      adapter: postgis
      encoding: utf8
      reconnect: false
      pool: 5
      username: {{ .Values.betyUser }}
      password: <%= ENV['BETYPASSWORD'] %>
      database: {{ .Values.betyDatabase }}
      host: {{ include "betydb.postgisHost" . }}
      port: {{ include "betydb.postgisPort" . }}
