apiVersion: v1
kind: Secret
metadata:
  name: {{ include "betydb.fullname" . }}
  labels:
{{ include "betydb.labels" . | indent 4 }}
type: Opaque
data:
{{- if .Values.betyPassword }}
  bety-password:  {{ .Values.betyPassword | b64enc | quote }}
{{- else }}
  bety-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
{{- if .Values.secretKey }}
  secretKey:  {{ .Values.secretKey | b64enc | quote }}
{{- else }}
  secretKey: {{ randAlphaNum 30 | b64enc | quote }}
{{- end }}
