{{- if .Values.monitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clowder.fullname" . }}-monitor
  labels:
{{ include "clowder.labels" . | indent 4 }}
spec:
  type: {{ .Values.monitor.service.type }}
  ports:
    - port: {{ .Values.monitor.service.port }}
      targetPort: monitor
      protocol: TCP
      name: monitor
  selector:
    app.kubernetes.io/name: {{ include "clowder.name" . }}-monitor
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
