apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgis.fullname" . }}
  labels:
{{ include "postgis.labels" . | indent 4 }}
type: Opaque
data:
{{- if .Values.postgresPassword }}
  postgres-password:  {{ .Values.postgresPassword | b64enc | quote }}
{{- else }}
  postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
