apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ include "postgis.fullname" . }}
  labels:
{{ include "postgis.labels" . | indent 4 }}
spec:
  #replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "postgis.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "postgis.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            {{- if .Values.postgresUser }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresUser | quote }}
            {{- end }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgis.fullname" . }}
                  key: postgres-password
            {{- if .Values.postgresDB }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresDB | quote }}
            {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U {{ .Values.postgresUser | quote }} -h 127.0.0.1 -p {{ .Values.service.port }}
            initialDelaySeconds: 240
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U {{ .Values.postgresUser | quote }} -h 127.0.0.1 -p {{ .Values.service.port }}
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
      {{- if not .Values.persistence.enabled }}
          emptyDir: {}
      {{- else }}
          persistentVolumeClaim:
        {{- if .Values.persistence.existingClaim }}
          {{- with .Values.persistence.existingClaim }}
            claimName: {{ tpl . $ }}
          {{- end }}
        {{- else }}
            claimName: {{ include "postgis.fullname" . }}
        {{- end }}
      {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
