{{ if .Values.bety.initialize }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "bety.fullname" . }}-init
  labels:
{{ include "bety.labels" . | indent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    "helm.sh/hook-weight": "5"
spec:
  template:
    metadata:
      name: {{ include "bety.fullname" . }}-init
      labels:
{{ include "bety.labels" . | indent 8 }}
    spec:
      {{- with .Values.hooks.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      restartPolicy: Never
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
        - name: db-init-job
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ["initialize"]
          env:
            - name: LOCAL_SERVER
              value: {{ .Values.bety.localServer | quote }}
            - name: PGHOST
              value: {{ .Values.postgis.postgresHost | quote }}
            - name: PGUSER
              value: {{ .Values.postgis.postgresUser | quote }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgis
                  key: postgres-password
            - name: BETYUSER
              value: {{ .Values.bety.username | quote }}
            - name: BETYPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: bety-password
            - name: BETYDATABASE
              value: {{ .Values.bety.database | quote }}
{{ end }}