apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bety.fullname" . }}-config
  labels:
{{ include "bety.labels" . | indent 4 }}
data:
  database.yaml: |-
    production:
      adapter: postgis
      encoding: utf8
      reconnect: false
      database: <%= ENV['BETYDATABASE'] %>
      pool: 5
      username: <%= ENV['BETYUSER'] %>
      password: <%= ENV['BETYPASSWORD'] %>
      host: {{ .Values.postgis.postgresHost | quote }}
      port: 5432
