apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bety.fullname" . }}
  labels:
{{ include "bety.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bety.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bety.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: bety
              containerPort: 8000
              protocol: TCP
          env:
            - name: UNICORN_WORKER_PROCESSES
              value: {{ .Values.bety.processes | quote }}
            - name: SECRET_KEY_BASE
              value: {{ .Values.bety.secretKey | quote }}
            - name: RAILS_RELATIVE_URL_ROOT
              value: {{ .Values.ingress.path | quote }}
            - name: LOCAL_SERVER
              value: {{ .Values.bety.localServer | quote }}
            - name: REMOTE_SERVERS
              value: {{ .Values.bety.remoteservers | quote }}
            - name: BETYUSER
              value: {{ .Values.bety.username | quote }}
            - name: BETYPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: bety-password
            - name: BETYDATABASE
              value: {{ .Values.bety.database | quote }}
          volumeMounts:
            - name: database-yaml
              mountPath: /home/bety/config/database.yml
          livenessProbe:
            httpGet:
              path: {{ .Values.ingress.path }}
              port: bety
              initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: {{ .Values.ingress.path }}
              port: bety
              initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: database-yaml
          configMap:
              name: database.yaml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
