{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "bety.fullname" }}
  labels:
{{ include "bety.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
      {{- if  .Values.ingress.hostName }}
        - {{ .Values.ingress.hostName }}
      {{- end }}
      secretName: {{  .Values.ingress.tlsSecret }}
{{- end }}
  rules:
  {{- if .Values.ingress.hostName }}
    - host: {{ .Values.ingress.hostName }}
      http:
  {{- else }}
    - http:
  {{- end }}
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ include "bety.fullname" }}
              servicePort: bety
{{- end }}
