apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "betydb.fullname" . }}-load-db
  labels:
{{ include "betydb.labels" . | indent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    "helm.sh/hook-weight": "5"
spec:
  template:
    metadata:
      name: {{ include "betydb.name" . }}-load-db
      labels:
{{ include "betydb.labels" . | indent 8 }}
    spec:
      {{- with .Values.hooks.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      restartPolicy: Never
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: check-postgresql
          image: pecan/check:test
          command: ['./check_postgresql']
          env:
{{ include "betydb.postgresqlEnv" . | indent 12 }}
      containers:
        - name: bety-init
          image: "pecan/db:{{ .Values.dbtag }}"
          imagePullPolicy: Always
          env:
{{ include "betydb.postgresqlEnv" . | indent 12 }}
{{ include "betydb.betydbEnv" . | indent 12 }}
