apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clowder.fullname" . }}-config
  labels:
{{ include "clowder.labels" . | indent 4 }}
data:
  play.plugins: |-
{{- if .Values.rabbitmq.enabled }}
    9992:services.RabbitmqPlugin
{{- end }}
{{- if .Values.elasticsearch.enabled }}
    10002:services.ElasticsearchPlugin
{{- end }}
  custom.conf: |-
    application.context="{{ .Values.ingress.path }}"
    securesocial.onLoginGoTo="{{ .Values.ingress.path }}"
    securesocial.onLogoutGoTo="{{ .Values.ingress.path }}"
    securesocial.ssl={{ .Values.ingress.ssl }}
    # security options
    application.secret="${CLOWDER_SECRET}"
    commKey="${CLOWDER_KEY}"
    # default admin and should admin approve everybody
    registerThroughAdmins={{ .Values.registerThroughAdmins }}
    initialAdmins={{ join "," .Values.initialAdmins | quote }}
    # email options
{{- if .Values.smtp.mock }}
    smtp.mock=true
{{- else }}
    smtp.host={{ .Values.smtp.host | default "stmp" | quote }}
{{- end }}
    # storage
{{- if .Values.storage.s3 }}
    service.byteStorage=services.s3.S3ByteStorageService
    clowder.s3.serviceEndpoint={{ .Values.storage.s3.endpoint | quote }}
    clowder.s3.bucketName={{ .Values.storage.s3.bucket | quote }}
{{- if .Values.storage.s3.region }}
    clowder.s3.region={{ .Values.storage.s3.region | quote }}
{{- end }}
    clowder.s3.accessKey={{ .Values.storage.s3.access_key | quote }}
    clowder.s3.secretKey={{ .Values.storage.s3.secret_key | quote }}
{{- else }}
    service.byteStorage=services.filesystem.DiskByteStorageService
    clowder.diskStorage.path="/home/clowder/data"
{{- end }}
    # mongo server
    mongodbURI={{ include "clowder.mongodburi" . | quote }}
{{- if .Values.rabbitmq.enabled }}
    # rabbitmq
    clowder.rabbitmq.uri={{ include "clowder.rabbitmquri" . | quote }}
    clowder.rabbitmq.exchange=clowder
{{- if .Values.fixRabbitmqClowderUrl }}
    clowder.rabbitmq.clowderurl="http://{{ include "clowder.clowderuri" . }}"
{{- end }}
{{- end }}
{{- if .Values.elasticsearch.enabled }}
    # elasticsearch
    elasticsearchSettings.clusterName="clowder"
    elasticsearchSettings.serverAddress="elasticsearch"
    elasticsearchSettings.serverPort=9300
{{- end }}
