apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clowder.fullname" . }}
  labels:
{{ include "clowder.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.commKey }}
  clowder-key:  {{ .Values.commKey | b64enc | quote }}
  {{- else }}
  clowder-key: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretKey }}
  clowder-secret:  {{ .Values.secretKey | b64enc | quote }}
  {{- else }}
  clowder-secret: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.user.enabled }}
    {{- if .Values.user.password }}
  user-password: {{ .Values.user.password | b64enc | quote }}
    {{- else }}
  user-password: {{ randAlphaNum 10 | b64enc | quote }}
    {{- end }}
  {{- end }}
