{{- if .Values.rstudio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pecan.fullname" . }}-rstudio
  labels:
{{ include "pecan.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.rstudio.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pecan.name" . }}-rstudio
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pecan.name" . }}-rstudio
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: check-rabbitmq
          image: "{{ .Values.image.project }}/check:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['./check_rabbitmq']
          env:
{{ include "pecan.env.rabbitmq" . | indent 12 }}
        - name: check-postgres
          image: "{{ .Values.image.project }}/check:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['./check_postgresql']
          env:
{{ include "pecan.env.postgres" . | indent 12 }}
        - name: check-betydb
          image: "{{ .Values.image.project }}/check:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['./check_betydb']
          env:
{{ include "pecan.env.betydb" . | indent 12 }}
      containers:
        - name: {{ .Chart.Name }}-rstudio-nginx
          image: "nginx:alpine"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.rstudio.ingress.path }}
              port: http
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
          resources:
            {{- toYaml .Values.rstudio.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-rstudio
          image: "{{ .Values.image.project }}/base:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/init"]
          env:
{{ include "pecan.env.rabbitmq" . | indent 12 }}
{{ include "pecan.env.postgres" . | indent 12 }}
{{ include "pecan.env.cluster" . | indent 12 }}
            - name: RABBITMQ_MGMT_PATH
              value: {{ .Values.rabbitmq.ingress.path | default "/" | quote }}
            - name: USER
              value: "carya"
            - name: PASSWORD
              value: "illinois"
          ports:
            - name: rstudio
              containerPort: 8787
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: rstudio
          readinessProbe:
            httpGet:
              path: /
              port: rstudio
          resources:
            {{- toYaml .Values.rstudio.resources | nindent 12 }}
      volumes:
        - name: nginx-conf
          configMap:
              name: {{ include "pecan.fullname" . }}-config
      {{- with .Values.rstudio.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.rstudio.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.rstudio.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}