apiVersion: v1
version: 0.1.0
name: pecan
appVersion: "1.7.0"
icon: https://isda.ncsa.illinois.edu/~kooper/charts/images/pecan.png
description: Web-interface to the Biofuel Ecophysiological Traits and Yields Database (used by PEcAn and TERRA REF)
home: https://www.pecanproject.org
maintainers:
- name: Rob Kooper
  email: kooper@illinois.edu
